// controllers/colorsController.js
const express = require("express");
const colors = express.Router();
const { getAllColors, getColor, createColor } = require("../queries/color");
const { checkBoolean, checkName } = require("../validations/checkColors.js");


// INDEX - localhost:3003, localhost:3003/colors
colors.get("/", async (req, res) => {
    const allColors = await getAllColors();
    if (allColors[0]) {
      res.status(200).json(allColors);
    } else {
      res.status(500).json({ error: "server error" });
    }
  });


// SHOW - localhost: 3003/colors/2 - individual 
colors.get("/:id", async (req, res) => {
  const { id } = req.params;
  const color = await getColor(id);
  if (color) {
    res.json(color);
  } else {
    res.status(404).json({ error: "not found" });
  }
});


//CREATE - localhost:3003/colors and then create a new array, id may be autogenerated
colors.post("/",checkBoolean, checkName, async (req, res) => {
  const color = await createColor(req.body);
  res.json(color);
});



module.exports = colors;

//Note: When making configuration changes, shut down your server entirely and start again. Configuration changes are often not tracked/reset with nodemon.